### ISSUE TITLE
It downloads an empty zip file. no video, nothing.

### ISSUE THREAD

**Issue by tamzid001** [th3k3y/TikDL#1]
it downloads an empty zip file. no video, nothing. 
[tiktok_videos (4).zip](https://github.com/th3k3y/TikDL/files/12198744/tiktok_videos.4.zip)

**Comment by rabbyt3s** [comment]
Hello ! Make sure you added your Rapid API key in the code and it should
work fine. If you did add your API key and it's still not working, please
send me another message.

Le ven. 28 juil. 2023 à 23:08, tamzid001 ***@***.***> a
écrit :

**Comment by tamzid001** [comment]
im very sorry but can u please guide me on how to find my api key in rapid api? i just created my account on rapidapi

**Comment by tamzid001** [comment]
when i go to this page, https://rapidapi.com/tiktok-downloader-download-tiktok-videos-without-watermark-tiktok-downloader-download-tiktok-videos-without-watermark-default/api/tiktok-downloader-download-tiktok-videos-without-watermark/
it says API not found

**Comment by tamzid001** [comment]
please share the rapid api link

**Comment by th3k3y** [comment]
https://rapidapi.com/maatootz/api/tiktok-downloader-download-tiktok-videos-without-watermark/

**Comment by rabbyt3s** [comment]
> please share the rapid api link

https://rapidapi.com/maatootz/api/tiktok-downloader-download-tiktok-videos-without-watermark/
